### ISSUE TITLE
`logger is not a function`

### ISSUE THREAD

**Issue by taina0407** [node-apn/node-apn#438]
Hello,
I've faced this issue today when testing APN with empty cert and key files.
Not a big issue but hope it can help you guys clean the code.
Used node-apn version 2.1.0

Unhandled rejection TypeError: logger is not a function
    at loadAndValidate (/xxxx/node_modules/apn/lib/credentials/certificate/prepare.js:16:7)
    at config (/xxxx/node_modules/apn/lib/config.js:47:22)
    at new Client (/xxxx/node_modules/apn/lib/client.js:11:19)
    at EventEmitter.Provider (/xxxx/node_modules/apn/lib/provider.js:12:19)

**Comment by Eliaschetouani** [comment]
I've the same problem...

**Comment by florianreinhart** [comment]
Thank you! This should be fixed in v2.1.1. Can you confirm?

**Comment by florianreinhart** [comment]
@taina0407 @Eliaschetouani This should be fixed in v2.1.1. Can you confirm?

**Comment by taina0407** [comment]
@florianreinhart : Sorry Florian, I'm quite busy on my project now so couldn't confirm that
