### ISSUE TITLE
Cant connect to Apple APN Gateway

### ISSUE THREAD

**Issue by lelandcope** [node-apn/node-apn#446]
I've tried every which way to export the cert but for some reason I am never able to connect. Im currently on v1.7.8 because this is an older app. When I startup the app I am getting the following error 

```
APN GATEWAY ERROR Error: 140735223549952:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1292:SSL alert number 46

  at SlabBuffer.use (tls.js:235:18)
  at CleartextStream.read [as _read] (tls.js:455:29)
  at CleartextStream.Readable.read (_stream_readable.js:341:10)
  at EncryptedStream.write [as _write] (tls.js:369:25)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at EncryptedStream.Writable.write (_stream_writable.js:183:11)
  at write (_stream_readable.js:602:24)
  at flow (_stream_readable.js:611:7)
  at Socket.pipeOnReadable (_stream_readable.js:643:5)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)
```

I have tried googling the error and I can't seem to find a fix. In keychain it is saying my cert is valid. I am using an exported p12 from keychain. Any help you can give me would be amazing and thank you for your time.

**Comment by florianreinhart** [comment]
It could be that your system doesn't trust the server certificate presented by APNs.

What's your OS and which node version are you using? Can also post a code snippet and show how you create your connection object.

**Comment by lelandcope** [comment]
OS: OS X El Capitan
Node: 0.10.35

```
var options = {
    pfx: path.resolve(__dirname, '../../apn/apn-cert-2016.p12'),
    production: true
};
var apnConnection = new apn.Connection(options);
```

It's weird because up until I needed to update my certificate this same exact code has been working perfectly.

Do you know how I can check if it's an issue with my system not trusting my certificate?

Thank you again for the help.

**Comment by florianreinhart** [comment]
Maybe APNs rejects your client certificate. Please try the steps mentioned in the wiki [Preparing-Certificates](https://github.com/node-apn/node-apn/wiki/Preparing-Certificates).
