### ISSUE TITLE
Problem caused by Buffer.from() call in Endpoint.js

### ISSUE THREAD

**Issue by zaumreit** [node-apn/node-apn#467]
According to [Node reference](https://nodejs.org/docs/v6.0.0/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe), Buffer.from() function is introduced in node version 6.0.0. , so it would cause TypeError while requiring this module in node v4.4.7.

> var apn = require('apn')
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (E:\hue-mobile-push\node_modules\apn\lib\protocol\endpoint.js:17:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\hue-mobile-push\node_modules\apn\index.js:27:18)
    at Module._compile (module.js:409:26)

**Comment by florianreinhart** [comment]
Actually `Buffer.from()` was introduced in [v4.5.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#4.5.0).

I only looked at the latest [v4 documentation](https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe) and assumed it was present in v4. Our tests run on the latest version of each Node.js release, so the CI didn't catch that.

Updating your node to v4.5.0 or higher should fix it for you.

**Comment by zaumreit** [comment]
Thank you for your quick reply and sorry for my mistake.
I have tried in higher node version and it works well.

I think it would be better to indicate the minimum Node version. 

Thank you. :)

**Comment by florianreinhart** [comment]
In the next release node engine will be set appropriately in `package.json`. This was just an oversight.
