### ISSUE TITLE
Unexpected token "," in `apn/index.js:28`

### ISSUE THREAD

**Issue by fourmationinc** [node-apn/node-apn#486]
I'm getting the following error when importing `node-apn`. Note that the app is being run through `pm2` and appears to run fine standalone. The error does occur in the `node-apn` module though so I thought I would ask here first.

```
 /www/international-texting-production/node_modules/apn/index.js:28
 	tls,
 ^
 SyntaxError: Unexpected token ,
     at Module._compile (module.js:439:25)
     at Object.Module._extensions..js (module.js:474:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:312:12)
     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
     at Module.require (module.js:364:17)
     at require (module.js:380:17)
     at Object.<anonymous> (myapp.js:3:11)
```

**Comment by oliversalzburg** [comment]
What Node version?

**Comment by fourmationinc** [comment]
Sorry, should've mentioned that initially. It's `6.2.2`.

**Comment by florianreinhart** [comment]
You are running an unsupported node version. Please use a node LTS release for node-apn, e.g. 6.9.2

**Comment by OpakAlex** [comment]
![На ХУЙ](http://risovach.ru/upload/2015/04/mem/stalin-rasstrelyat_78621063_orig_.jpg)
