### ISSUE TITLE
TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by comfiger** [node-apn/node-apn#489]
/Users/comfiger/Desktop/www/apns/node_modules/apn/lib/protocol/endpoint.js:17
const CLIENT_PRELUDE = Buffer.from("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");
                              ^
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/Users/comfiger/Desktop/www/apns/node_modules/apn/lib/protocol/endpoint.js:17:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/comfiger/Desktop/www/apns/node_modules/apn/index.js:27:18)
    at Module._compile (module.js:409:26)

**Comment by thelinuxkid** [comment]
Same here:
`TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/apps/node-apps/wn-api/node_modules/apn/lib/protocol/endpoint.js:17:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.<anonymous> (/apps/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Function.cls_wrapMethod [as _load] (/apps/node-apps/wn-api/node_modules/newrelic/lib/shimmer.js:256:38)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/apps/node-apps/wn-api/node_modules/apn/index.js:27:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.<anonymous> (/apps/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)`

**Comment by oliversalzburg** [comment]
What Node version?

**Comment by thelinuxkid** [comment]
v4.4.7

**Comment by voidprady** [comment]
const CLIENT_PRELUDE = Buffer.from("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");
                              ^

Node version 4.2.6

**Comment by oliversalzburg** [comment]
You need at least 4.6 for node-apn

**Comment by sebastienbarbier** [comment]
I had same problem, updating node fixed it.
