### ISSUE TITLE
Endpoint error: connect ECONNREFUSED 17.188.138.73:2195

### ISSUE THREAD

**Issue by lavkesh1608** [node-apn/node-apn#511]
Hi , 

I am getting below error , please check , my node version is V7.0.0 and node -apn is "apn": "^2.1.2",
 Also my provider option is as follow : 

options = {
		/*passphrase : '',*/
		production:false,
		port : 2195,
		key : keyPemFile,
		cert : certificateFile, 

	};

# Error

`{ VError: endpoint error: connect ECONNREFUSED 17.188.138.73:2195
    at Endpoint.endpoint.on.err (/home/project/node_modules/apn/lib/protocol/endpointManager.js:69:32)
    at emitOne (events.js:96:13)
    at Endpoint.emit (events.js:188:7)
    at Endpoint.error [as _error] (/home/project/node_modules/apn/lib/protocol/endpoint.js:99:10)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT ### (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  jse_shortmsg: 'endpoint error',
  jse_cause: 
   { Error: connect ECONNREFUSED 17.188.138.73:2195
       at Object.exports._errnoException (util.js:1026:11)
       at exports._exceptionWithHostPort (util.js:1049:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '17.188.138.73',
     port: 2195 },
  jse_info: {},
  message: 'endpoint error: connect ECONNREFUSED 17.188.138.73:2195' }`

**Comment by oliversalzburg** [comment]
So connection is refused on the custom port you're setting. Why are you setting a custom port?

**Comment by lavkesh1608** [comment]
Thanks @oliversalzburg  , i am passing that becas needed in old version. I removed port and its working now. and option is 

                                   options = {
                                        /*passphrase : '',*/
                                       production:false,
                                       key : keyPemFile,
                                       cert : certificateFile,
                                     };
