### ISSUE TITLE
TypeError: Cannot set property 'title' of null

### ISSUE THREAD

**Issue by AndySoHotRightNow** [node-apn/node-apn#513]
Hi,

I just came across what I believe could be a bug.

I have a function defined as follows:

```
var send = function (body, contentAvailable, title, tokenIos) {

    // Setup the notification:
    var notification = new apn.Notification();

    notification.badge = 1;
    notification.body = body;
    notification.contentAvailable = contentAvailable ? 1 : 0;
    notification.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
    notification.sound = title ? "ping.aiff" : null;
    notification.title = title;
    
    // Etc.
```

When I try sending a "silent" notification (with `body = null`, `contentAvailable = true` and `title = null`) I get the following error:

```
TypeError: Cannot set property 'title' of null
    at Object.title (/home/ubuntu/app/node_modules/apn/lib/notification/apsProperties.js:37:24)
    at send (/home/ubuntu/app/notification.js:114:24)
    at /home/ubuntu/app/notification.js:58:9
    at /home/ubuntu/app/notification.js:46:16
    at /home/ubuntu/app/db.js:29:16
    at .<anonymous> (/home/ubuntu/app/node_modules/pg/node_modules/pg-pool/index.js:104:11)
    at Query.handleReadyForQuery (/home/ubuntu/app/node_modules/pg/lib/query.js:114:10)
    at .<anonymous> (/home/ubuntu/app/node_modules/pg/lib/client.js:172:19)
    at emitOne (events.js:101:20)
    at emit (events.js:188:7)
    at Socket.<anonymous> (/home/ubuntu/app/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

The error therefore appears to be traceable to this setter method in apsProperties.js (line 37):

```
set title(value) {
    this.prepareAlert();
    this.aps.alert.title = value;
},
```

And in turn, the reason why the alert property is `null` can be found here (line 15):

```
set body(value) {
    if (typeof this.aps.alert !== "object") {
      this.aps.alert = value;
    }
    else {
      this.prepareAlert();
      this.aps.alert.body = value;
    }
},
```

Due to the fact that `this.aps.alert !== "object"` is true and I am setting the body (as well as the title of the notification) to `null` an exception is thrown.

Am I doing something wrong? Thank you in advance.

**Comment by oliversalzburg** [comment]
I *think* if you want to achieve what you're looking for, `body` should be `undefined` not `null`. Optimally, don't set the body/title at all if `send` is not provided with one.

**Comment by AndySoHotRightNow** [comment]
Right, that's exactly how I'm going about it now and it's not a big deal.

Just thought that perhaps it would be useful to highlight this behavior for re-factoring/resiliency purposes.

Thanks anyway!
