### ISSUE TITLE
Base64 Decode Error when using APNS Auth Key

### ISSUE THREAD

**Issue by Gonzalo1987** [node-apn/node-apn#524]
I'm getting the same error that:
[https://github.com/node-apn/node-apn/issues/440](https://github.com/node-apn/node-apn/issues/440)

I'm using node.js version 6.9.4.

I have two enviroments, with the same version of node.js in two servers, one of which works (windows) and one other not (linux).

I'm getting this result: 
VError: Failed to generate token: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
at prepareToken (/myfolder/apns/node_modules/apn/lib/credentials/token/prepare.js:35:13)
at config (/myfolder/apns/node_modules/apn/lib/config.js:41:31
[...]

I don't know what is happening, but this don't seems to be only a problem of version 5 of node.js.

I really would apreciate any help, idea or solution.

**Comment by Gonzalo1987** [comment]
Solved:
For future references:
https://github.com/pyca/cryptography/issues/3232
