### ISSUE TITLE
Thousands tokens

### ISSUE THREAD

**Issue by vyacheslavk** [node-apn/node-apn#557]
Does any one have an issue sending thousands tokens per connection? I have node: v7.8.0 and latest node-apn, when i sending about 2954 tokens i don't have any callback. When number of tokens less than 100 everything is okey. Also not often getting warning
`(node:3518) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 wakeup listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by SkogDev** [comment]
I have the same problem on iOS. I solved it by dividing the array and sending in chunks.

**Comment by ded** [comment]
@vyacheslavk for what it's worth, and to follow up on @SkogDev's answer, I did the same thing, and here is a snippet of code that I send over to our push server.. it involves using Bluebirds `Promise.all` and lodash's `_.chunk` (neither of which are necessary, but demonstrates the point)

``` js
exports.push = function sendMessage(token, message, optUrl) {
  if (!config.options.notifications) return Promise.resolve({
    ok: true
  })
  let tokens = token.push ? token : [token]
  return Promise.all(_.chunk(tokens, 50).map(function (t) {
    return new Promise(function (resolve, reject) {
      request({
        method: 'post',
        url: `https://${config.push_host}/push`,
        json: {
          tokens: t,
          message: message,
          url: optUrl || '',
          env: config.push_env
        }
      },
      function (err, resp, body) {
        if (err) reject(err)
        else resolve(body)
      })
    })
  }))
}```

**Comment by matgenois** [comment]
I have the same issue when sending about 1300 tokens. Then, if I send them in chunk of 100, it seems like APNs block the 4th and subsequent connection attempts. I receive this message for each token I tried to send :

`apn write failed: Not receiving Ping response after 150000ms `

Here's my code : 

```
    //This function receive a chunk of 100 iOS devices
    function pushIosNotifications(iosLocalizedDevices, notificationData, lang) {

        log.debug ('Sending iOS Notification for language ' + lang + ' Number of iOS devices this promise will notify :', iosLocalizedDevices.length);

        if (!iosLocalizedDevices || iosLocalizedDevices.length === 0) return;
        var registrationIds = _.map(iosLocalizedDevices, 'registrationId');

        var iosNotificationData = new apn.Notification();
        iosNotificationData.payload = {
            alfredNotificationType: notificationData.type,
            alfredNotificationKey: notificationData.key,
            alfredNotificationId: notificationData.id
        };
        iosNotificationData.topic = topic;
        iosNotificationData.title = sprint(notificationData.title[lang], notificationData.titleParams);
        iosNotificationData.body = sprint(notificationData.message[lang], notificationData.messageParams);
        iosNotificationData.priority = 10;
        iosNotificationData.contentAvailable = true;

        var apnsLog = [];
        var deleteRegId = [];
        return apnProvider.send(iosNotificationData, registrationIds).then(function(result){
            log.debug('APN Notification sent! result : ', result);
            if (result.failed && result.failed.length > 0) {
                for (var j = 0; j < result.failed.length; j++) {
                    var reason = 'unknown';
                    if (result.failed[j] && result.failed[j].response && result.failed[j].response.reason) {
                        reason = result.failed[j].response.reason;
                    } else if (result.failed[j] && result.failed[j].error && result.failed[j].error.message) {
                        reason = result.failed[j].response.reason;
                    }
                    var userDevice = _.find(iosLocalizedDevices, function (d) {
                        return d.registrationId === result.failed[j].device;
                    });

                    var status = {
                        platform: 'ios',
                        device: result.failed[j].device,
                        userName: userDevice.userName,
                        ts: new Date(),
                        status: 'failed (' + result.failed[j].status + ')',
                        reason: reason
                    };
                    if (result.failed[j].status === '400' || result.failed[j].status === '410') {
                        status.status = 'failed (' + result.failed[j].status + ') - will delete this token from devices collection.';
                        deleteRegId.push(deviceRegistrationService.removeDeviceByRegistrationId(result.failed[j].device));
                    }
                    apnsLog.push(status);
                }
            }
            if (result.sent && result.sent.length > 0) {
                for (var j = 0 ; j < result.sent.length ; j++) {
                    var userDevice = _.find(iosLocalizedDevices, function(d) {
                        return d.registrationId === result.sent[j].device;
                    });
                    var status = {
                        platform : 'ios',
                        device : result.sent[j].device,
                        userName : userDevice.userName,
                        ts: new Date(),
                        status : 'success'
                    };
                    apnsLog.push(status)
                }
            }

            return Promise.all(deleteRegId).then(function() {
                //Updating status for token sent
            });
        }).catch(function(err){
            log.debug('Error when sending iOS notifications.', err);
            return false;
        });
}
```

On the APNs troubleshooting page, they say we shouldn't have any problems about sending 9000 tokens in 1 second. So I don't really understand what is wrong. Any tips would be appreciated.

**Comment by SamDecrock** [comment]
I'm using async.eachSeries() to send multiple notifications: https://github.com/caolan/async

**Comment by tri613** [comment]
I am having this problem too, 
I have about 60k devices to send, and I'm splitting them in to chunks of 1000,
using a new provider for each chunk and it is just get stuck after about 10 chunks...
I have tried using only one provider for all devices but no success for this also.

I don't have a server for this, instead I'm using a simple node script only...
Is there any update or ways to achieve this? Any help would be appreciated.
Thanks.

**Comment by wiggisser** [comment]
I got stuck today on this issue too. Currently I only tried up to 700 devices with one call. Sometimes this works like a charm, sometimes it works 2 times in a row. But when sending such a block, after a while the send() promise does not return, neither with resolve nor with reject. My current workaournd is to call send for each and every token separately with a timeout of 5ms after each of them ... Not the ideal solution but seems to work for now ...

**Comment by dpmooney** [comment]
Same issue.

When I send silent notifications, I can send them in blocks of 1000.  When I try notifications with a notification body to them, it seems to fail after the first block.  I need to send 10000+ notifications.

**Comment by andreialecu** [comment]
Getting hit by this also. I'm not sure why it suddenly started happening. Here's some code I'm using to work around it:

```
        var deviceChunks = _.chunk(devices, 100);
        async.eachSeries(deviceChunks, (devices, callback) => {
            this.apnconn.send(note, devices).then(result => {
                callback(null, result)
            }).catch(callback);
        }, function(err) {
            if (err) {
                ctx.done(err);
            } else {
                ctx.done(null, {dispatched: true});
            }
        });
```

**Comment by jdelman** [comment]
This is a serious problem. The library does not work as described. The title of this issue does not effectively convey the gravity of this problem.

Other people are having the same problem: https://groups.google.com/forum/#!topic/node-apn/K7Usuz0pcSU

@andreialecu - when using batches of 100, how many total notifications are you sending out?

**Comment by vyacheslavk** [comment]
@jdelman I also divided 15k of devices to 100 and timeout for 4sec, it takes about an hour to send all notifications, because that i switched to GO [sideshow/apns2](https://github.com/sideshow/apns2) and it handles it in sec

**Comment by andreialecu** [comment]
I'm sending up to 5k and it finishes in a few seconds with the batches of 100. Sometimes (though relatively rarely) however it seems to hang. It's not entirely predictable with `eachSeries` as in my workaround above.

FWIW, you may have better results with older node versions. Node 4.x I think should be fine. I only started seeing this problem after upgrading Node.

**Comment by andreialecu** [comment]
### Since I still had problems with this I decided to make a new library that can act as a drop in replacement, and which uses the **native** `http2` module that is now part of `nodejs 8.8.1+`.

You can find it here: https://github.com/andreialecu/node-apn-http2 and on npm/yarn as `node-apn-http2`.

In my app I was able to simply change `require('apn')` to `require('node-apn-http2')` and have everything still work properly (and much faster).

Keep in mind that only the core functionality is implemented, but so far it seems to be working fine. I'll be monitoring it, and if anyone finds any issues and wants to contribute please let me know. 

I started from scratch because the code related to `http2` is pretty complex and didn't exactly translate into the native module API very well.

**Comment by florianreinhart** [comment]
Can you test with v3.0.0-alpha1 if this is still an issue? I was able to send a notification to 20k devices in 10s.

**Comment by rudyzeinoun** [comment]
I am having this issue even with v3.0.0-alpha1. On 1.7.8, things were going very well. I tried using parallel-batch to split into batches of 1000, but the problem still persists.
Note that I also tried with node-apn-http2 and the issue exists there too!

**Comment by evansnicholas** [comment]
We also started experiencing this issue after upgrading from node 4 to node 6.  We batch tokens into groups of 1000 and provider.send hangs in the process of sending the notifications.  I am considering implementing the solution that @wiggisser suggested.  Any idea what the root cause of this issue is?  Seems odd that the version of node should have anything to do with it.

**Comment by Watermanman** [comment]
I am switched to v3.0.0-alpha1, because i have memory leak issue on v2.1.5 for me.
It does not have memory leak, But i got new issue on v3.0.0-alpha1 when i running 6 hours.
I am use pm2 with babel-node to run test code.

my test code:
```
const apn = require('apn');
const option = {
    cert: "77-cert.pem",
    key: "77-key.pem",
    production: true
}
const testFunc = () => {
    let apnProvider = new apn.Provider(option)
    let deviceToken = "2fc6d41f8f3f6bb3e48a986ed2b008319063ae2405ac20be3776991abfdd5138" 
    let note = new apn.Notification();

    note.expiry = Math.floor(Date.now / 1000) + 3600
    note.badge = 1
    note.topic = "test topic"
    note.alert = "test alert"
    note.payload = "test payload"

    apnProvider.send(note, deviceToken).then((result) => {
        if (result.failed.length === 1) {
            console.log('@failed@', result.failed);         
        }
        apnProvider.shutdown();    
    })
        .catch(err => {
            console.log('@err@', err)
        });
}
setInterval(() => { testFunc() }, 2);  //send a push per 0.002s 
```

PM2 log and error:

```
@failed@ [ { device: '2fc6d41f8f3f6bb3e48a986ed2b008319063ae2405ac20be3776991abfdd5138',
    error:
     { VError: stream ended unexpectedly
    at ClientHttp2Stream.request.on (/Users/danny/Desktop/pushTest/node_modules/apn/lib/client.js:120:23)
    at emitNone (events.js:111:20)
    at ClientHttp2Stream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
       jse_shortmsg: 'stream ended unexpectedly',
       jse_info: {},
       message: 'stream ended unexpectedly' } } ]

Error: EMFILE: too many open files, open '77-cert.pem'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at resolveCredential (/Users/danny/Desktop/pushTest/node_modules/apn/lib/credentials/resolve.js:16:15)
    at loadCredentials (/Users/danny/Desktop/pushTest/node_modules/apn/lib/credentials/certificate/load.js:12:16)
    at loadAndValidate (/Users/danny/Desktop/pushTest/node_modules/apn/lib/credentials/certificate/prepare.js:11:20)
    at config (/Users/danny/Desktop/pushTest/node_modules/apn/lib/config.js:49:22)
    at new Client (/Users/danny/Desktop/pushTest/node_modules/apn/lib/client.js:21:19)
    at new Provider (/Users/danny/Desktop/pushTest/node_modules/apn/lib/provider.js:12:19)
    at testFunc (/Users/danny/Desktop/pushTest/index.js:181:23)
    at Timeout._onTimeout (/Users/danny/Desktop/pushTest/index.js:216:19)
```

I think this problem is fd(file descriptor) has been reached on linux, Is `shutdown()` can not solve this problem?

**Comment by oliversalzburg** [comment]
Seems like this ticket is starting to become the collection area for any issues resulting from large send batches, while the original reporter has already moved to a different solution and is unlikely to verify suggestions at this time. I think this issue should be closed and people should start their own threads for their specific issue.

@Watermanman From your test code, it's clear that you're creating a new provider instance for every push. Don't do that, especially not in your production code. You can also read the certificate yourself and only pass the contents. Then you can control the file descriptor handle in your code. But that shouldn't be necessary as long as you stick to a single provider instance.

The warning `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 wakeup listeners added.`, seen in the original report, is also an indication of constructing too many providers.

Regardless, node-apn tries to create a socket connection for every single token:
https://github.com/node-apn/node-apn/blob/master/lib/provider.js#L29

The problem is not only with the amount of promise instances, but they certainly play a role. A lot of resources are triggered to try and send as many notifications concurrently as possible. That approach is not ideal, but generally assures that sends are processed as fast as possible and possibly resulting errors can be controlled through the batch size passed to the provider.

Resolving this requires the implementation of batching or queueing and no solution would be ideal for everyone. If you're sending such large volumes of notifications, you need to think about your approach and not just dump thousands of tokens into node-apn and hope for the best. This IMHO should be solved in user code, not in the library.

I also gave sideshow/apns2 a look and it seems to me like their API doesn't even allow you to pass multiple recipients per notification, thus sidetracking the entire issue and moving the solution into user code. Go's threading model also allows for completely different approaches to the problem. In Node, the natural thing to usually do is to run multiple processes and distribute your workload between them.

**Comment by wiggisser** [comment]
@oliversalzburg So instead of a library solving the problem, every user should solve it on it's own? I strongly disagree here. Why would I need the library in this case? If one develops a library to support a specific use case, one should also solve the resulting problems. I agree, there may not be an easy "one fits all" solution, but I think the most obvious use cases should be covered. 

In my case, I think the problems where caused by the http2 implementation and connection pooling. If there were too many requests, the Promises just stopped returning, ie they neither rejected nor resolved. And that even with batch sizes of only 50 devices. I moved to go in the meantime, where I'm really able to send hundreds and thousands of tokens in a few seconds.

**Comment by oliversalzburg** [comment]
@wiggisser Ideally, only the affected users solve it. We've been using this library for several years and I have never had any issues like this. 

The issue is solved by a simple loop; this shouldn't pose a challenge to developers. I think the biggest mistake in this library is that the interface even allows you to specify multiple receivers, suggesting that it will work properly without any additional work for the user.

I prefer a lightweight component that can be extended as needed. I don't like libraries that try to solve every problem and fail. Creating a composition from simple components is a lot easier than getting complex libraries to work together.

But I also believe that there are several failure cases (especially over time) that have all made their way into this thread. For some it was the early HTTP2 implementation, maybe in combination with large batch sizes. But the underlying issue is how the library processes those batches. If you're seeing failures with 50 receivers, then it's certainly a different failure than for those with thousands of receivers. Faulty HTTP2 implementations will probably just amplify the batch processing issue.
