### ISSUE TITLE
Crashing on Heroku

### ISSUE THREAD

**Issue by PCrompton** [node-apn/node-apn#563]
This library works fine for me locally but when I push to Heroku it's giving me the following error: 

```
2017-05-01T22:16:35.379426+00:00 heroku[web.1]: Starting process with command `node server.js`
2017-05-01T22:16:38.916870+00:00 app[web.1]: Environment: production
2017-05-01T22:16:39.649095+00:00 app[web.1]: /app/node_modules/apn/lib/protocol/endpoint.js:17
2017-05-01T22:16:39.649106+00:00 app[web.1]: const CLIENT_PRELUDE = Buffer.from("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");
2017-05-01T22:16:39.649107+00:00 app[web.1]:                               ^
2017-05-01T22:16:39.649108+00:00 app[web.1]: 
2017-05-01T22:16:39.649109+00:00 app[web.1]: TypeError: this is not a typed array.
2017-05-01T22:16:39.649110+00:00 app[web.1]:     at Function.from (native)
2017-05-01T22:16:39.649111+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/apn/lib/protocol/endpoint.js:17:31)
2017-05-01T22:16:39.649111+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2017-05-01T22:16:39.649112+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2017-05-01T22:16:39.649112+00:00 app[web.1]:     at Module.load (module.js:357:32)
2017-05-01T22:16:39.649113+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2017-05-01T22:16:39.649113+00:00 app[web.1]:     at Module.require (module.js:367:17)
2017-05-01T22:16:39.649114+00:00 app[web.1]:     at require (internal/module.js:16:19)
2017-05-01T22:16:39.649114+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/apn/index.js:27:18)
2017-05-01T22:16:39.649115+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2017-05-01T22:16:39.649115+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2017-05-01T22:16:39.649116+00:00 app[web.1]:     at Module.load (module.js:357:32)
2017-05-01T22:16:39.649117+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2017-05-01T22:16:39.649117+00:00 app[web.1]:     at Module.require (module.js:367:17)
2017-05-01T22:16:39.649118+00:00 app[web.1]:     at require (internal/module.js:16:19)
2017-05-01T22:16:39.649118+00:00 app[web.1]:     at Object.<anonymous> (/app/services/apn.js:1:73)
2017-05-01T22:16:39.766556+00:00 heroku[web.1]: State changed from starting to crashed
```

Does anyone know why I'm getting this error, and if there is a version of this module that will work on Heroku?

Thanks

-Paul

**Comment by PCrompton** [comment]
Never mind, I realized my node versions were not in sync
