### ISSUE TITLE
Unexpected token tls,

### ISSUE THREAD

**Issue by sojharo** [node-apn/node-apn#567]
On `require('apn')` I am getting the following error:

    /root/CloudKibo/node_modules/apn/index.js:28
      tls,
         ^
    SyntaxError: Unexpected token ,
        at Module._compile (module.js:439:25)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/root/CloudKibo/server/config/socketio.js:771:11)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)

**Comment by florianreinhart** [comment]
You are probably using an outdated node version.

**Comment by sojharo** [comment]
Oh, yes I am using an outdated node version. Is there any workaround for this or I will have to update to the latest version?

**Comment by sojharo** [comment]
I was able to solve this issue with new version of the nodejs. However, I am having the following error now:

    VError: Failed to generate token: error:0906D06C:PEM routines:PEM_read_bio:no start line
        at prepareToken 
    (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/credentials/token/prepare.js:45:13)
        at config (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/config.js:42:31)
        at new Client (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/client.js:11:19)
        at EventEmitter.Provider 
    (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/provider.js:12:19)
        at Object.<anonymous> (/Users/sojharo/Projects/CloudKibo/server/config/socketio.js:773:16)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/sojharo/Projects/CloudKibo/server/app.js:64:1)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)

The same error happened on this library too, but they solved by some other method which I can't do with this library.

https://github.com/raix/push/issues/163

**Comment by sojharo** [comment]
The above error came when I used cert.pem in key field in apn.Provider(). This is other error when I use key.pem at the same place:

```
VError: Failed to generate token: Could not find expected "seq"
    at prepareToken (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/credentials/token/prepare.js:45:13)
    at config (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/config.js:42:31)
    at new Client (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/client.js:11:19)
    at EventEmitter.Provider (/Users/sojharo/Projects/CloudKibo/node_modules/apn/lib/provider.js:12:19)
    at Object.<anonymous> (/Users/sojharo/Projects/CloudKibo/server/config/socketio.js:773:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sojharo/Projects/CloudKibo/server/app.js:64:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

I am using the following documentation guide.

https://github.com/node-apn/node-apn/blob/master/doc/apn.markdown

**Comment by sojharo** [comment]
I couldn't find in documentation where to put p8 or p12 file as discussed in following issue:

https://github.com/node-apn/node-apn/issues/552#issuecomment-292148387
