### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by nabeegii** [node-apn/node-apn#570]
hello, im getting this while waiting for a response from send method, node-apn version is 2.1.4 and node version is 7.10.0, someone please help regarding this, thanks

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: Unknown flag for frame type SETTINGS: isNull
    at Function.writeCommonHeader [as commonHeader] (/Users/user/Desktop/stuff/apps/Whatever App/Whatever-server-code/node_modules/http2/lib/protocol/framer.js:223:5)
    at Serializer._transform (/Users/user/Desktop/stuff/apps/Whatever App/Whatever-server-code/node_modules/http2/lib/protocol/framer.js:44:27)
    at Serializer.Transform._read (_stream_transform.js:167:10)
    at Serializer.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Serializer.Writable.write (_stream_writable.js:241:11)
    at Compressor.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Compressor.emit (events.js:191:7)

**Comment by florianreinhart** [comment]
This looks like an error in the HTTP/2 module. Is anyone else seeing this?

@nabeegii Do you always get this error or does ist sometimes work?

**Comment by nabeegii** [comment]
evertime i try, I'm using code as told in readme
