### ISSUE TITLE
Constant VError: apn write failed: Not receiving Ping response after 150000 ms

### ISSUE THREAD

**Issue by zaiddag** [node-apn/node-apn#583]
This is happening consistently in our production servers... Not sure what the cause could be.
We use a single Provider with a p8 token.

Latest APN
Node 7.6.0
AWS Beanstalk
Amazon Linux v4.1.1

**Comment by pungme** [comment]
we're having the same problem, any workaround?

**Comment by zaiddag** [comment]
Read there was a hack:
Make a new provider ~ every hour
```javascript
let provider = new apn.Provider({})
setInterval(() => {
    provider.shutdown()
    provider = new apn.Provider({})
}, 1000 * 60 * 58)
```

For us, we spun up a docker microservice of gorush and route all our pushes through there.

**Comment by funkenstrahlen** [comment]
This is broken for me too!

**Comment by funkenstrahlen** [comment]
@florianreinhart Can you take a look at this?

**Comment by PhroZenOne** [comment]
For us the error pops up after sending to a lot of tokens. Could it be that APNS blocks the connection for some flooding reason?

**Comment by hopye** [comment]
im having the same , was testing earlier on sending push to one or two users several times, then hours after i try to send a push thru parse dashboard to all and a single user.. not working..

ERR! parse-server-push-adapter APNS     at Array.forEach (native)
ERR! parse-server-push-adapter APNS     at EventEmitter.close [as _close] (/opt/bitnami/apps/parse/htdocs/node_modules/apn/lib/protocol/endpoi
nt.js:139:33)
ERR! parse-server-push-adapter APNS     at emitOne (events.js:101:20)
ERR! parse-server-push-adapter APNS     at TLSSocket.emit (events.js:188:7)
ERR! parse-server-push-adapter APNS     at _handle.close (net.js:497:12)
ERR! parse-server-push-adapter APNS     at TCP.done [as _onclose] (_tls_wrap.js:332:7)
ERR! parse-server-push-adapter APNS   jse_shortmsg: 'apn write failed: Not receiving Ping response after 150000 ms',

**Comment by hopye** [comment]
No fix yet ?

**Comment by hopye** [comment]
No fix yet ????

**Comment by hopye** [comment]
😮 still no fix ?

**Comment by oliversalzburg** [comment]
@hopye Yes, still no fix

**Comment by edengol** [comment]
Yeah just got this today, add it to my memory leak issues.
node 6.11.1
apn 2.1.5

**Comment by funkenstrahlen** [comment]
bump

**Comment by funkenstrahlen** [comment]
@florianreinhart Do you think 3.0 will solve this issue?

**Comment by florianreinhart** [comment]
Yes, I think so.

Though currently 3.x does not have a ping functionality like 2.x did. We added that ping feature to work around an issue with the old HTTP/2 lib and APNs. So it might not be needed after all.

It'd be great if you could give 3.0.0 a try. It's been really stable for me. It's just labeled as alpha because HTTP/2 support in node is still experimental.

**Comment by edengol** [comment]
@florianreinhart I just started today running `3.0.0-alpha1` after updating to node `8.9.3` and things seem to be running smoothly, just FYI. I'll ping back if I run into problems.

**Comment by hopye** [comment]
Hey @edengol , please let us know after testing it for at least 2 weeks :)

**Comment by edengol** [comment]
@hopye 14 days of running with `3.0.0-alpha1` and node `8.9.3`, with a single `APNProvider` (i.e. never shutdown or restarted) tens of thousands APNs sent, no ping error, no memory leak error, no other errors.

**Comment by funkenstrahlen** [comment]
Great to hear this is working fine in first tests!

**Comment by hopye** [comment]
Hey @edengol Nice to Hear!!.. can you instruct me a bit ? i had to down grade parse-server alltgether to 2.4.2 , should i update parse-server and then.. update node-apn to that alpha version ? how do i update it ? i dont see any branch 3.0.0-alpha1 on the repo .. :/

**Comment by hopye** [comment]
npm install apn@3.0.0-alpha1
Sorry :/ lol

**Comment by hopye** [comment]
Just got a problem. apn using 3.0.0-alpha1 ,  parse-server 2.7.1 , parse-dashboard 1.1.2 , When going to the push section. It hangs, the three balls * activity indicator* .. just hangs there.. nothing to show..

**Comment by hopye** [comment]
But has nothing to do with apn. The parse-dashboard 1.1.2 has this, bug. the fix is to add the supportedpushlocales with an empty array.

{
```
  "apps": [{
    "serverURL": "http://localhost:1337/parse",
    "appId": "app-id-here",
    "masterKey": "master-key-here",
    "appName": "app-name-here",
    "supportedPushLocales": []
  }],
}
```

**Comment by funkenstrahlen** [comment]
I will also test 3.0 on my staging machine. Will not deploy this on production as long as it is in alpha.

**Comment by funkenstrahlen** [comment]
First test on my test backend using 3.0.0-alpha1 looks fine. Push notifications can be send successfully.

I can not confirm the ping bug is gone though because there are only very few push clients on my test backend. Therefore the ping error never occurred on my test backend in the past.

@edengol Do you know when `nodejs` does plan to release http2 support officially?

**Comment by iainreid820** [comment]
> Read there was a hack:
> Make a new provider ~ every hour
> 
> ```js
> let provider = new apn.Provider({})
> setInterval(() => {
>     provider.shutdown()
>     provider = new apn.Provider({})
> }, 1000 * 60 * 58)
> ```
> 
> For us, we spun up a docker microservice of gorush and route all our pushes through there.

I think we'll implement this hack, although the `setTimeout` might cause service shutdown issues with the held reference.
