### ISSUE TITLE
apn Module initialisation error: Error: certificate and key do not match

### ISSUE THREAD

**Issue by ntlzz93** [node-apn/node-apn#597]
I pushed success some noti but sometime it threw me this error and crash my push server. I'm using version 1.7.8. Please help!!!

```
apn Module initialisation error: Error: certificate and key do not match
    at validateCredentials (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/apn/lib/credentials/validate.js:7:9)
    at /home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/apn/lib/connection.js:163:5
    at _fulfilled (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:816:13)
    at /home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:624:44
    at runSingle (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:137:13)
    at flush (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) +34ms
  apn Raising error: 513 { encoding: 'utf8',
  payload:
   { data:
      { t: 'Test mo deeplink',
        m: 'ABCxyz',
        n: 'PsM',
        ac: 4,
        l: 'https://tips.moneylover.me/add-tiki',
        ca: 'aaa' },
     aps:
      { badge: undefined,
        sound: 'default',
        alert: [Object],
        'content-available': 1,
        'url-args': undefined,
        category: undefined } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"data":{"t":"Test mo deeplink","m":"ABCxyz","n":"PsM","ac":4,"l":"https://tips.moneylover.me/add-tiki","ca":"aaa"},"aps":{"sound":"default","alert":{"body":"ABCxyz","action-loc-key":"Open"},"content-available":1}}',
  truncateAtWordEnd: false,
  _alert: { body: 'ABCxyz', 'action-loc-key': 'Open' },
  _sound: 'default',
  _contentAvailable: 1 } Device {
  token: <Buffer c8 59 fe f9 76 42 48 1f ff 82 11 76 82 fe 0b 23 b5 86 8d da da df fc c7 c5 db d0 8c 02 4b a3 4c> } +0ms
/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:155
                throw e;
                ^

Error: certificate and key do not match
    at validateCredentials (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/apn/lib/credentials/validate.js:7:9)
    at /home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/apn/lib/connection.js:163:5
    at _fulfilled (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:816:13)
    at /home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:624:44
    at runSingle (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:137:13)
    at flush (/home/money-sync/ml-push-notification-services-test/ml-push-notification-service/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ntlzz93** [comment]
I have sent successfully some push notification with certificate and key, but sometime it still throw me this error

**Comment by florianreinhart** [comment]
Have you tried generating a new certificate?
