### ISSUE TITLE
provider shutdown in v3.0.0-alpha1

### ISSUE THREAD

**Issue by mikemliu** [node-apn/node-apn#633]
There is no `shutdown` method in `Http2Session`. Needs to change to `this.session.close`. Tested on node v8.11.3

```
Client.prototype.shutdown = function shutdown(callback) {
    if (this.session && !this.session.destroyed) {
      this.session.close(() => {
        this.session.destroy();
        if (callback) {
          callback();
        }
      });
    }
  };
```

**Comment by primeare** [comment]
Any changes here? The code proposed by @mikemliu works well and resolves the issue.

**Comment by ssypi** [comment]
+1, occurs on v8.12.0, needs to be fixed.

```
TypeError: this.session.shutdown is not a function
    at Client.shutdown (node_modules/apn/lib/client.js:144:20)
    at Provider.shutdown (node_modules/apn/lib/provider.js:46:17)
```

From quick check on the documentation, session.close() seems to do the same as currently used shutdown({graceful:true})

```
http2session.close([callback])

Gracefully closes the Http2Session, allowing any existing streams to complete on their own and preventing new Http2Stream instances from being created. Once closed, http2session.destroy() might be called if there are no open Http2Stream instances.
```
