### ISSUE TITLE
Error: Command failed: yarn add react-native --exact

### ISSUE THREAD

**Issue by srujanreddy2015** [node-apn/node-apn#634]
E:\REACT-NATIVE PROJACTS>react-native init learn
This will walk you through creating a new React Native project in E:\REACT-NATIVE PROJACTS\learn
Using yarn v1.9.4
Installing react-native...
yarn add v1.9.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[---------------------------------------------------------------------------------------------------------------] 0/615(node:12160) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error An unexpected error occurred: "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz: error:0906D06C:PEM routines:PEM_read_bio:no start line".
info If you think this is a bug, please open a bug report with the information provided in "E:\\REACT-NATIVE PROJACTS\\learn\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
{ Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at run (C:\Users\toshiba\AppData\Roaming\npm\node_modules\react-native-cli\index.js:294:5)
    at createProject (C:\Users\toshiba\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\toshiba\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\Users\toshiba\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10312,
  stdout: null,
  stderr: null }
Command `yarn add react-native --exact` failed.

**Comment by ptsimon** [comment]
Any solution?

**Comment by oliversalzburg** [comment]
Why is an issue with `react-native` reported here?

**Comment by oliversalzburg** [comment]
@mehulnahar Try reporting the issue in the appropriate project.
