### ISSUE TITLE
http2 error with Nodejs 8.14.0

### ISSUE THREAD

**Issue by ArtemisMucaj** [node-apn/node-apn#640]
Hi,

I've upgraded my Nodejs version to 8.14.0, lately I've been observing a strange behavior on _node-apn@3.0.0-alpha_ with the way HTTP2 GOAWAY messages are handled.

Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY, at ClientHttp2Session.request (internal/http2/core.js:1424:13), at Client.write (/home/node/node_modules/apn/lib/client.js:82:34)

From what I understand of node-apn, a new http2 client should be created on GOAWAY messages but here it doesn't seem to be the case. I haven't had the time to investigate yet but hopefully I'll be able to this week!

**Comment by doubliez** [comment]
I'm observing the same behavior. Running Nodejs 8.14.0 and node-apn 3.0.0-alpha1.

I'm instantiating the Provider once and never call shutdown (both because of https://github.com/node-apn/node-apn/issues/633 and because it doesn't seem right to instantiate a new Provider for each notification). But then after running for a while, sending notifications starts failing with the error that @ArtemisMucaj mentioned.

It seems reasonable that node-apn should create a new http2 session after receiving a GOAWAY, which should fix this issue.

**Comment by ArtemisMucaj** [comment]
I've been running #642 and #643 in production for two weeks without any issues

@florianreinhart would you consider not using an `alpha` tag for 3.x versions and accepting PRs ? :)
