### ISSUE TITLE
VError: stream ended unexpectedly

### ISSUE THREAD

**Issue by SebC99** [node-apn/node-apn#653]
When trying to send the same payload to multiple devices, I end up with this apn error

```
node-pre-gyp ERR! parse-server-push-adapter APNS  APNS error transmitting to device %s with error %s d1af72a027a7241a313c2b7d7e76006f989adfb044e35db60484a865853dd0e4 { VError: stream ended unexpectedly
node-pre-gyp ERR! parse-server-push-adapter APNS     at ClientHttp2Stream.request.on (node_modules/apn/lib/client.js:120:23)
node-pre-gyp ERR! parse-server-push-adapter APNS     at ClientHttp2Stream.emit (events.js:189:13)
node-pre-gyp ERR! parse-server-push-adapter APNS     at ClientHttp2Stream.EventEmitter.emit (domain.js:441:20)
node-pre-gyp ERR! parse-server-push-adapter APNS     at endReadableNT (_stream_readable.js:1103:12)
node-pre-gyp ERR! parse-server-push-adapter APNS     at process._tickCallback (internal/process/next_tick.js:63:19)
node-pre-gyp ERR! parse-server-push-adapter APNS   jse_shortmsg: 'stream ended unexpectedly',
node-pre-gyp ERR! parse-server-push-adapter APNS   jse_info: {},
node-pre-gyp ERR! parse-server-push-adapter APNS   message: 'stream ended unexpectedly',
node-pre-gyp ERR! parse-server-push-adapter APNS   stack:
node-pre-gyp ERR! parse-server-push-adapter APNS    'VError: stream ended unexpectedly\n    at ClientHttp2Stream.request.on (node_modules/apn/lib/client.js:120:23)\n    at ClientHttp2Stream.emit (events.js:189:13)\n    at ClientHttp2Stream.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' }
node-pre-gyp ERR! parse-server-push-adapter APNS VError: stream ended unexpectedly
node-pre-gyp ERR! parse-server-push-adapter APNS     at ClientHttp2Stream.request.on (node_modules/apn/lib/client.js:120:23)
node-pre-gyp ERR! parse-server-push-adapter APNS     at ClientHttp2Stream.emit (events.js:189:13)
node-pre-gyp ERR! parse-server-push-adapter APNS     at ClientHttp2Stream.EventEmitter.emit (domain.js:441:20)
node-pre-gyp ERR! parse-server-push-adapter APNS     at endReadableNT (_stream_readable.js:1103:12)
node-pre-gyp ERR! parse-server-push-adapter APNS     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by scookies** [comment]
I am seeing the same, was there a workaround?
