### ISSUE TITLE
ERR_HTTP2_GOAWAY_SESSION with @parse/node-apn 3.1.0 and node 12

### ISSUE THREAD

**Issue by eliw00d** [node-apn/node-apn#685]
We are getting the following error:
```
Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY
   at ClientHttp2Session.request (internal/http2/core.js:1590:13)
   at Client.write (/node_modules/@parse/node-apn/lib/client.js:99:34)
   at /node_modules/@parse/node-apn/lib/provider.js:29:62
   at CoreDocumentArray.map (<anonymous>)
   at CoreDocumentArray.map (/node_modules/mongoose/lib/types/documentarray.js:42:27)
   at Provider.send (/node_modules/@parse/node-apn/lib/provider.js:29:36)
```
I found [this related issue](https://github.com/node-apn/node-apn/issues/640) but it would seem this should have been fixed. Are we missing something?

**Comment by maxmijn** [comment]
Any update on this? We are also getting this error on about 1 out of 100 notifications we send on production.
