### ISSUE TITLE
How to use P12 files to send pushes

### ISSUE THREAD

**Issue by mikemilla** [node-apn/node-apn#725]
I am using a P12 generated the same way as this tutorial: https://youtu.be/jq42brrSg28

Here is what my code looks like:

```javascript
const apn = require('apn');

async function test() {

  var deviceToken = 'a_volid_device_token_for_the_same_app';

  var apnProvider = new apn.Provider({
    pfx: 'Certificates.p12',
    passphrase: 'password',
    production: false
  });
  
  let notification = new apn.Notification();

  notification.alert = {
    title: 'Hey',
    body: 'Whats up'
  };
  
  const res = await apnProvider.send(notification, deviceToken)
  console.log(res)

}

test()
```

I get the following error in the console when running:

```json
{
  sent: [],
  failed: [
    {
      device: 'f6209a7b84f17e4fa601e2a37b53937ff2843c24cc86eee2b7f1a0393555fbe3',
      error: Error: unsupported
          at configSecureContext (node:internal/tls/secure-context:277:15)
          at Object.createSecureContext (node:_tls_common:117:3)
          at Object.connect (node:_tls_wrap:1629:48)
          at Endpoint.connect [as _connect] (/Users/xxx/Desktop/Folders/test/node_modules/apn/lib/protocol/endpoint.js:87:37)
          at new Endpoint (/Users/xxx/Desktop/Folders/test/node_modules/apn/lib/protocol/endpoint.js:44:10)
          at EndpointManager.createEndpoint (/Users/xxx/Desktop/Folders/test/node_modules/apn/lib/protocol/endpointManager.js:51:22)
          at EndpointManager.getStream (/Users/xxx/Desktop/Folders/test/node_modules/apn/lib/protocol/endpointManager.js:32:12)
          at /Users/xxx/Desktop/Folders/test/node_modules/apn/lib/client.js:121:43
          at new Promise (<anonymous>)
          at Client.getStream (/Users/xxx/Desktop/Folders/test/node_modules/apn/lib/client.js:120:12)
    }
  ]
}
```

What is going on here? What am I missing?

**Comment by mikemilla** [comment]
Anybody know what's going on here?

**Comment by mtrezza** [comment]
I can confirm that I've also observed the issue, but on Node 18, but not on Node 16 or 14.

**Comment by mikemilla** [comment]
This is a node 18 issue. Thanks @mtrezza. Downgrading to node 16 works.

Would still be nice to find a working solution for node 18

**Comment by mtrezza** [comment]
To be exact, it's more a certificate cipher issue than a Node issue.

**Comment by ayushforcebolt** [comment]
"An 'error: unsupported' message may occur in Node.js 17 RC2 because the legacy OpenSSL provider is disabled by default. If you enable the --openssl-legacy-provider flag, it should work as expected."

Ref:- [https://github.com/nodejs/node/issues/40672](url)

How to enable flag:- node --openssl-legacy-provider index.js(Root file)

**Comment by ayushforcebolt** [comment]
> Anybody know what's going on here?

You have to enable --openssl-legacy-provider

**Comment by dchahla** [comment]
bad cert handling try easy-apn (npm) it should fix your problem. no deps! 7.7kb unpacked.

**Comment by Meyssam120** [comment]
As a workaround: Instead of using the .p12 you can use the certificate and key you used to generate the p12.
```
cert: "./certs/signerCert.pem",
key: "./certs/signerKey.pem",
passphrase: "yourPW"
```

**Comment by calitb** [comment]
Just in case you are like me and generate the p12 in Mac Keychain.

For me following these steps made the p12 work for me.

https://www.docuseal.com/docs/convert-legacy-p12-pfx-files-to-support-openssl-3


( I ended up using https://github.com/parse-community/node-apn too )
