### ISSUE TITLE
Unfortunately this library plain doesn't work (2024) - it looks for cert.pem even if you're using PATs

### ISSUE THREAD

**Issue by smhk** [node-apn/node-apn#738]
per the doco:

```
var apn_options = {
	token: {
		key: p8key,  // try file, string, etc
		keyId: "PL62KVXW34",
		teamId: "BGP36TQ2W7"
	},
	production: true
}
var apnProvider = new apn.Provider(apn_options)

```
result ...

```
node:fs:581
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open 'cert.pem'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:460:35)
    at resolveCredential (/home/ubuntu/main/node_modules/apn/lib/credentials/resolve.js:16:13)
    at loadCredentials (/home/ubuntu/main/node_modules/apn/lib/credentials/load.js:11:13)
    at loadAndValidate (/home/ubuntu/main/node_modules/apn/lib/credentials/prepare.js:11:20)
    at config (/home/ubuntu/main/node_modules/apn/lib/config.js:38:20)
    at new Client (/home/ubuntu/main/node_modules/apn/lib/client.js:11:19)
    at new Provider (/home/ubuntu/main/node_modules/apn/lib/provider.js:12:19)
    at Object.<anonymous> (/home/ubuntu/main/main.js:545:19)
    at Module._compile (node:internal/modules/cjs/loader:1378:14) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'cert.pem'
}

```

I tried setting cert to null, etc .. no good.

Shame!

**Comment by efeder-amd** [comment]
I'm still using this library. I set the value of `key` to the base64 value of the p8 file generated from my Apple developer account.
So run `base64 <filename>.p8` and put the resulting value at `apn_options.token.key`

**Comment by demjm** [comment]
> I'm still using this library. I set the value of `key` to the base64 value of the p8 file generated from my Apple developer account. So run `base64 <filename>.p8` and put the resulting value at `apn_options.token.key`

Hi @efeder-amd ! by any chance could you share a working example ? Thanks a lot!

**Comment by efeder-amd** [comment]
Imagine you run `base64 <filename>.p8` and it generates the following string to stdout:
```
5I9e3725GPTcLD3/8wGX0ClCqxE7Vv3M3eNJHoNPMs0mJ4i
rQlLiio7JVAwyXOWgDNcBzKm/kKF0NLYJuZ0u2hC9e+CrJiXF
UrCAq+zfncX+5Q4KF3Kf0FVCZOkfP2snoyqRMvEHYvCt6Ktd
vKU11C1FnyZQVgl16UBL3ln5RCaCkxQYi+A8Ws/0hUreJUseb
65ozU86AEstdCF8XhgoQ/7SojGIoA==
```

Then you can set your options apn.Provider like so:
```javascript
var b64_key = `5I9e3725GPTcLD3/8wGX0ClCqxE7Vv3M3eNJHoNPMs0mJ4i
rQlLiio7JVAwyXOWgDNcBzKm/kKF0NLYJuZ0u2hC9e+CrJiXF
UrCAq+zfncX+5Q4KF3Kf0FVCZOkfP2snoyqRMvEHYvCt6Ktd
vKU11C1FnyZQVgl16UBL3ln5RCaCkxQYi+A8Ws/0hUreJUseb
65ozU86AEstdCF8XhgoQ/7SojGIoA==`;

var apn_options = {
	token: {
		key: Buffer.from(b64_key, 'base64')
		keyId: "PL62KVXW34",
		teamId: "BGP36TQ2W7"
	},
	production: true
}
var apnProvider = new apn.Provider(apn_options)
```

**Comment by demjm** [comment]
Thanks @efeder-amd !
I managed to make it work with the apns2 library, and using a key as is. I’m satisfied with the result and it was much more simple to implement 😄

**Comment by cbaker6** [comment]
An updated version of this library including a number of new features such as broadcasting and managing channels is here: https://github.com/parse-community/node-apn. You can see the additions in the release notes https://github.com/parse-community/node-apn/releases
